### ISSUE TITLE
Scene이동 시 생기는 버그

### ISSUE THREAD

**Issue by dlwjdeo** [jsg0912/beat_warrior#19]
Player가 dontDestroyOnLoad에 2개 생김
MiniMap의 PlayerIcon이 인게임 화면에 보임

**Comment by Nights-SDH** [comment]
Player 2개 생기는 것은 이미 있는지 확인을 안하고 무조건 만들어 생기는 버그로 확인하고 생성하도록 수정함
MiniMap은 MainCamera가 안잡혔을 때 생기는 버그인데, Main Camera가 안잡혀있으면 Main Camera를 잡도록 수정함
