### ISSUE TITLE
MiniMap Bug

### ISSUE THREAD

**Issue by Nights-SDH** [jsg0912/beat_warrior#2]
미니맵 아이콘이 깜빡이면서 뜨지 않는 버그 고치기
프리펩 위치, 크기에 영향 받지 않게 하기
미니맵 아이콘 hierarchy창에 뜨는 것들 정리해서 표기하기

**Comment by jsg0912** [comment]
미니맵 아이콘이 깜빡이면서 뜨지 않는 버그 고치기, 프리펩 위치, 크기에 영향 받지 않게 하기
- 카메라 범위 인식된 내용을 처리하는 과정에서 오류가 있어서 미니맵에서 써야하는 정보만 받아오는 함수를 작성하여 인식하지 못하는 문제를 해결

미니맵 아이콘 hierarchy창에 뜨는 것들 정리해서 표기하기
- ObjectPool 코드 수정하면서 ObjectPooler에 아이콘 생성되도록 변경
