### ISSUE TITLE
벽 타일 Tag 추가

### ISSUE THREAD

**Issue by mingku87** [jsg0912/beat_warrior#3]
Base나 Tile 제외 벽들은 Wall 등의 새로운 Tag 추가 필요
(플레이어가 벽에 붙어있다가 떨어지면 FALL 상태로 변하는 버그 발생)

**Comment by Nights-SDH** [comment]
Assignees와 Labels을 추가해주세요

**Comment by Nights-SDH** [comment]
Tag와 Layer의 각 내용 설명 부탁드립니다
및 디폴트 또는 안쓰는거 제거 필요

**Comment by dlwjdeo** [comment]
Wall Tag추가했습니다

**Comment by dlwjdeo** [comment]
GameTag Rule 추가
Layer는 게임개발이 더 진행 되고 필요한 것들 위주로 정리할 예정입니다
