### ISSUE TITLE
In Game UI가 Don'tDestoryOnLoad에 있는데 맞는가?

### ISSUE THREAD

**Issue by Nights-SDH** [jsg0912/beat_warrior#4]
Unity Scene을 재시작하면 In Game UI가 2군데 있음
그리고 현재는 없지만 InGame에서 OutGame으로 가면 InGameUI기능이 사용 가능하게 되는 버그가 있을 것 같음

**Comment by dlwjdeo** [comment]
아마 setActive 켜져있을 때 인게임 조작을 못하게 bool값 추가하면 될듯
시간나면 하겠습니다

**Comment by dlwjdeo** [comment]
DontDestroyOnLoad는 게임 정보를 씬이 넘어가도 유지되기 때문에 UI에 필요해 보임
